version: '3.4'
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana_oem_app
    volumes:
      - ./plugins:/var/lib/grafana/plugins
    user: "0"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=Welcome1
      - GF_INSTALL_PLUGINS=/var/lib/grafana/plugins/oracle-emcc-app-2.0.0.zip;oracle-emcc-app
    restart: unless-stopped
    ports:
      - 3000:3000
